17:34:20.37 <ERROR> UnauthorizedError: token验证失败！
    at Object.throw (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa\lib\context.js:91:11)
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\tools\checkToken.js:12:22)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:345:16
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:42:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:43:18)
    at _callee$ (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:134:22)
    at tryCatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:9:191)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:9:437 (in errorHandle.js:27)
Call Stack:
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\middlewares\errorHandle.js:27:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
17:36:28.48 <ERROR> UnauthorizedError: token验证失败！
    at Object.throw (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa\lib\context.js:91:11)
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\tools\checkToken.js:12:22)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:345:16
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:42:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:43:18)
    at _callee$ (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:134:22)
    at tryCatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:9:191)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:9:437 (in errorHandle.js:27)
Call Stack:
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\middlewares\errorHandle.js:27:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
17:37:00.67 <ERROR> UnauthorizedError: token验证失败！
    at Object.throw (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa\lib\context.js:91:11)
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\tools\checkToken.js:12:22)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:345:16
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:42:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:43:18)
    at _callee$ (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:134:22)
    at tryCatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:9:191)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:9:437 (in errorHandle.js:27)
Call Stack:
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\middlewares\errorHandle.js:27:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
17:37:38.03 <ERROR> UnauthorizedError: token验证失败！
    at Object.throw (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa\lib\context.js:91:11)
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\tools\checkToken.js:12:22)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:345:16
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:42:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:43:18)
    at _callee$ (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:134:22)
    at tryCatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:9:191)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:9:437 (in errorHandle.js:27)
Call Stack:
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\middlewares\errorHandle.js:27:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
17:37:40.39 <ERROR> UnauthorizedError: token验证失败！
    at Object.throw (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa\lib\context.js:91:11)
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\tools\checkToken.js:12:22)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:345:16
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:42:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:43:18)
    at _callee$ (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:134:22)
    at tryCatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:9:191)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:9:437 (in errorHandle.js:27)
Call Stack:
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\middlewares\errorHandle.js:27:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
16:48:20.80 <ERROR> InternalServerError: 标签类型不能为空！
    at Object.throw (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa\lib\context.js:91:11)
    at editTag (C:\Users\Administrator\Desktop\v-k-blog\server\controllers\tag.js:50:18)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\tools\checkToken.js:18:11)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:345:16
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:42:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:43:18)
    at _callee$ (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:134:22)
    at tryCatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:299:22) (in errorHandle.js:27)
Call Stack:
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\middlewares\errorHandle.js:27:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
16:48:22.52 <ERROR> InternalServerError: 标签类型不能为空！
    at Object.throw (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa\lib\context.js:91:11)
    at editTag (C:\Users\Administrator\Desktop\v-k-blog\server\controllers\tag.js:50:18)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\tools\checkToken.js:18:11)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:345:16
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:42:32)
    at next (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\koa-compose\index.js:43:18)
    at _callee$ (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_koa2-cors@2.0.3@koa2-cors\dist\index.js:134:22)
    at tryCatch (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Administrator\Desktop\v-k-blog\server\node_modules\_regenerator-runtime@0.11.0@regenerator-runtime\runtime.js:299:22) (in errorHandle.js:27)
Call Stack:
    at module.exports (C:\Users\Administrator\Desktop\v-k-blog\server\middlewares\errorHandle.js:27:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
